apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-gateway-bets
  namespace: contour-operator
spec:
  gatewayClassRef: contour-gatewayclass
  networkPublishing:
    envoy:
      type: NodePortService
      # nodePorts are auto-assigned by k8s if unspecified.
      nodePorts:
        - name: http
          portNumber: 30080
        - name: https
          portNumber: 30443