apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: bets
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.3.1
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status