apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: contour-installation/gateway
    repoURL: https://github.com/claudioed/contour-gateway-linkerd.git
    targetRevision: HEAD
  destination:
    namespace: projectcontour
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true